### ISSUE TITLE
细化文档说明

### ISSUE THREAD

**Issue by mrcaidev** [mrcaidev/thermoflash#11]
对整个过程中会请求的 API 和 POST 的数据作出说明

**Comment by mrcaidev** [comment]
见本项目 Wiki

**Comment by MrPeterJin** [comment]
一个Wiki细化的建议：
判断学生是否在学校这一步骤应当细化说明...?（如果我没理解错代码的话）这份 api 是调用学校的数据库以此判断学生是否还在学校然后返回字典中 `returned` `unreturned` 的信息吧？

**Comment by mrcaidev** [comment]
> 一个Wiki细化的建议： 判断学生是否在学校这一步骤应当细化说明...?（如果我没理解错代码的话）这份 api 是调用学校的数据库以此判断学生是否还在学校然后返回字典中 `returned` `unreturned` 的信息吧？

API 返回的，能判断在校状态的字段是

- `schoolStatus`：0 或 1。
- `schoolStatusStr`：“在校”或“离校”。

这确实会调取学校的数据库，但我认为“调取数据库”是学校要干的事，而对我们开发来说是可以屏蔽不计的，所以当时并未加进 Wiki。

至于字典中 `returned` 和 `unreturned` 的具体数据，是另外向 `monitorRegisterForReturned` 和 `monitorRegister` 这两个站点抓取得到的，和 `checkBind` 这个站点并无关系。
