### ISSUE TITLE
加入超时最大重试功能

### ISSUE THREAD

**Issue by MrPeterJin** [mrcaidev/thermoflash#12]
![image](https://user-images.githubusercontent.com/51412849/150456365-9afb6c54-a1a3-4573-ac70-38cd956d8c4f.png)
![image](https://user-images.githubusercontent.com/51412849/150456257-2b7f9493-3acb-4700-a54c-9b1e6fa3a814.png)
如图所示，在自动运行中会发生访问 api 超时的情况（非 cookie 原因，已经手动重试，见图），建议添加  `maximumRetry` 或类似方式确保上报。

**Comment by mrcaidev** [comment]
感谢思路，已解决！详情可见 "src/reporters/_abstract.py"。

**Comment by MrPeterJin** [comment]
![image](https://user-images.githubusercontent.com/51412849/150621169-bfdf929c-08f2-4b55-9df9-864d72dcde12.png)

今日自动化部署仍然失败，是否程序语法有误？

**Comment by mrcaidev** [comment]
自动化教程已经全新改版，请参考 [Wiki](https://github.com/mrcaidev/thermoflash/wiki/%E7%94%B5%E5%AD%90%E7%A7%91%E6%8A%80%E5%A4%A7%E5%AD%A6)
