### ISSUE TITLE
每日填报系统更新，原有api失效

### ISSUE THREAD

**Issue by ZbWeR** [mrcaidev/thermoflash#14]
## 问题描述

开学后每日填报只需要填写一个体温即可，与之前需要填写三个体温不同，原有的api失效

原有api:https://jzsz.uestc.edu.cn/wxvacation/api/epidemic/monitorRegister
现访问效果：
{ "code":50022, "data":null, "message":"请求方法不支持", "otherData":{ "detail":"Request method 'GET' not supported" }, "status":false }

**Comment by mrcaidev** [comment]
已修改,请 fetch upstream 以检查效果.
