### ISSUE TITLE
获取sessionId问题

### ISSUE THREAD

**Issue by morgan-bo** [mrcaidev/thermoflash#16]
## 问题描述

成电智慧学工这个公众号现在研究生身份无权访问应用，自然也得不到体温测量通知，请问是否有其他途径获取sessionId？

**Comment by mrcaidev** [comment]
1. 这个项目是针对本科生编写的，研究生不知道能不能用；
2. `sessionId` 的确有别的方式可以获得，比如可以使用手机抓包软件（如 HttpCanary）在进入小程序时抓包，一般肯定能抓到一个以 `checkRegisterNew` 结尾的包；这个包里就有 `sessionId`。

**Comment by morgan-bo** [comment]
> 1. 这个项目是针对本科生编写的，研究生不知道能不能用；
> 2. `sessionId` 的确有别的方式可以获得，比如可以使用手机抓包软件（如 HttpCanary）在进入小程序时抓包，一般肯定能抓到一个以 `checkRegisterNew` 结尾的包；这个包里就有 `sessionId`。

谢谢！
