### ISSUE TITLE
为什么感觉main.yml里的配置不太对啊

### ISSUE THREAD

**Issue by ciwomuli** [mrcaidev/thermoflash#3]
00:30运行不应该是30 16 * * *吗

**Comment by MrCaiDev** [comment]
我也不是很懂，他这个workflow的时间很奇怪，我按正常时间写是不准的，然后去看了原仓库的schedule是0 16，我就直接照着写了发自我的华为平板-------- 原始邮件 --------发件人： ciwomuli ***@***.***>日期： 2021年9月9日周四 15:24收件人： MrCaiDev/uestc_temperature ***@***.***>抄送： Subscribed ***@***.***>主    题： [MrCaiDev/uestc_temperature] 为什么感觉main.yml里的配置不太对啊 (#3)

00:30运行不应该是30 16 * * *吗

**Comment by MrCaiDev** [comment]
我也不是很懂，他这个workflow的时间很奇怪，我按正常时间写是不准的，然后去看了原仓库的schedule是0 16，我就直接照着写了，不知道有没有后来的佬解释一下

**Comment by mrcaidev** [comment]
1. `0 16 * * *` 指的是 UTC 时间的 16:00，换算成北京时间（UTC+8）就是 24:00；
2. 因为 `schedule` 在 Github 的 workflow 运行的高负载期间（比如每个整点的刚开始），事件可能会延迟，所以就大概会推迟到 00:30 的样子。
> [Github Action的 Schedule 运行不准时的解决办法](https://zhuanlan.zhihu.com/p/379365305)
