### ISSUE TITLE
用户不存在

### ISSUE THREAD

**Issue by zzxupp** [mrcaidev/thermoflash#4]
公众号中学号无法登陆，提示用户不存在，用其他人的也不行，很奇怪！可否考虑从“https://eportal.uestc.edu.cn/jkdkapp/sys/lwReportEpidemicStu/index.do?#/dailyReport”直接入手？

**Comment by mrcaidev** [comment]
研究生的代码可能会有一些不一样；我是本科生，这个网站我没办法进入，但我会把研究生的自动填报提上TODO的！谢谢支持！

**Comment by mrcaidev** [comment]
研究生如果从网页端打卡的话，应该直接F12抓包就可；思路相同，对特定网址post即可。
