### ISSUE TITLE
或许可以更新一下教程

### ISSUE THREAD

**Issue by ciwomuli** [mrcaidev/thermoflash#5]
Actions默认是不开启的 或许应该在教程里写一下开启的方法

**Comment by MrCaiDev** [comment]
(ﾟOﾟ)我这边默认是开启的，你如果愿意的话可以帮我从Fork的人的视角写一下教程，然后PR就行(^-^)

**Comment by mrcaidev** [comment]
已经修正README说明，流程比较简单就不放具体图了
