### ISSUE TITLE
[Bug]TCP连接不能正确返回连接池

### ISSUE THREAD

**Issue by ghost** [mrcaidev/thermoflash#6]
我启动的第一个action中有全部的报错信息
> Reporting for student No.1...HTTPSConnectionPool(host='jzsz.uestc.edu.cn', port=443): Max retries exceeded with url: /wxvacation/monitorRegisterForReturned (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000024272DACAC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
连续两次启动都出现这个问题，感觉不是偶然

目前尝试在header加上 **'Connection': 'close'** 字段后，问题得到解决
希望对你有帮助，感谢你提供的项目

**Comment by mrcaidev** [comment]
这个bug今天是第一次出现，之前从来没有过…我自己今天自动打卡也失败了，我会马上排查原因的

**Comment by mrcaidev** [comment]
已做出修复。
原因应该是连接数超过最大限制，现做出相应两项调整：
1. 在程序开始前，睡眠0-10s内某个随机秒数。
2. `headers`内添加`{'Connection': 'close'}`。
如果第二天还是出现类似问题，将考虑在`get`时设`verify=False`。

**Comment by mrcaidev** [comment]
隔了一天后又出现了相同问题，现已设置`get`和`post`时的`verify=False`，测试手动运行能够成功。

**Comment by mrcaidev** [comment]
偶尔还是会有自动化失败……但是手动运行是可以成功的，不知道有没有后来的大佬看看怎么回事
