### ISSUE TITLE
实现学号密码打卡

### ISSUE THREAD

**Issue by mrcaidev** [mrcaidev/thermoflash#8]
之前需要用户手动抓包获取 `cookie`，希望能实现用户提供学号密码就能自动登录、获取 `cookie`、并打卡。

**Comment by DDLLFEV** [comment]
你好，我抓取的cookie中只有一个asessionid，和要求的格式不对，请问是如何抓取正确的sessionid？

**Comment by mrcaidev** [comment]
> 你好，我抓取的cookie中只有一个asessionid，和要求的格式不对，请问是如何抓取正确的sessionid？

![68747470733a2f2f73322e6c6f6c692e6e65742f323032322f30312f32332f326641517a4f52636543756b46536e2e706e67](https://user-images.githubusercontent.com/78269445/161406732-1c8f1068-683b-4fd7-a388-6e699449ea66.png)

这张图应该写的挺清晰的了；要注意是从公众号里进入，而不是小程序。

**Comment by cf-pages** [comment]
https://idas.uestc.edu.cn/authserver/login?service=https%3A%2F%2Fjzsz.uestc.edu.cn%2Fepidemic

通过这个链接或许可以实现用账号密码登录打卡，但是学校的统一身份验证页面，所以有滑动验证码，比较麻烦，估计需要用selenium等方式才行，登录成功后会跳转，跳转的页面的cookie中可以获得sessionid

**Comment by mrcaidev** [comment]
> https://idas.uestc.edu.cn/authserver/login?service=https%3A%2F%2Fjzsz.uestc.edu.cn%2Fepidemic
> 
> 通过这个链接或许可以实现用账号密码登录打卡，但是学校的统一身份验证页面，所以有滑动验证码，比较麻烦，估计需要用selenium等方式才行，登录成功后会跳转，跳转的页面的cookie中可以获得sessionid

确实，selenium 的方法我之前考虑过，但是滑动验证码我暂时解决不了；
感觉要上 CV 太麻烦了，或者就是要依赖[超级鹰](http://www.chaojiying.com/)这样的第三方验证码破解平台（不过要花钱）

**Comment by cf-pages** [comment]
> > https://idas.uestc.edu.cn/authserver/login?service=https%3A%2F%2Fjzsz.uestc.edu.cn%2Fepidemic
> > 通过这个链接或许可以实现用账号密码登录打卡，但是学校的统一身份验证页面，所以有滑动验证码，比较麻烦，估计需要用selenium等方式才行，登录成功后会跳转，跳转的页面的cookie中可以获得sessionid
> 
> 确实，selenium 的方法我之前考虑过，但是滑动验证码我暂时解决不了； 感觉要上 CV 太麻烦了，或者就是要依赖[超级鹰](http://www.chaojiying.com/)这样的第三方验证码破解平台（不过要花钱）

这里找到了一些校友写的过统一登录滑动验证码的代码，或许可以参考一下？
https://github.com/b71db892/AutoCheckInUESTC/blob/main/driver.py
https://github.com/onion-rain/uestc_health_report/blob/main/slide.py
https://github.com/YannLeo/UESTC_student_health_report/blob/main/morning.py
https://github.com/JhonarraonCSDN/Health_ClockIn_UESTC/blob/main/Health_ClockIn.py

**Comment by mrcaidev** [comment]
感谢，第二个很有用！但近几个月事情比较多，没有办法维护这个项目，等事情少了会尽快更新的！

**Comment by mrcaidev** [comment]
> 这里找到了一些校友写的过统一登录滑动验证码的代码，或许可以参考一下？ https://github.com/b71db892/AutoCheckInUESTC/blob/main/driver.py https://github.com/onion-rain/uestc_health_report/blob/main/slide.py https://github.com/YannLeo/UESTC_student_health_report/blob/main/morning.py https://github.com/JhonarraonCSDN/Health_ClockIn_UESTC/blob/main/Health_ClockIn.py

感谢，第二个很有用！但近几个月事情比较多，没有办法维护这个项目，等事情少了会尽快更新的！
