### ISSUE TITLE
一种方便的获取 sessionId 的方法

### ISSUE THREAD

**Issue by callG** [mrcaidev/thermoflash#9]
在“每日填报”界面复制链接，就可以看到 `https://jzsz.uestc.edu.cn/epidemic2/?sessionId=*****************#/pages/main/login/login`

**Comment by MrCaiDev** [comment]
“每日填报”界面指的是手机微信界面？还是 PC 版的抓包？

**Comment by mrcaidev** [comment]
> 在“每日填报”界面复制链接，就可以看到 `https://jzsz.uestc.edu.cn/epidemic2/?sessionId=*****************#/pages/main/login/login`

“每日填报”界面指的是手机微信界面？还是 PC 版的抓包？

**Comment by callG** [comment]
> > 在“每日填报”界面复制链接，就可以看到 `https://jzsz.uestc.edu.cn/epidemic2/?sessionId=*****************#/pages/main/login/login`
> 
> “每日填报”界面指的是手机微信界面？还是 PC 版的抓包？

微信-成电智慧学工-体温测量通知 点开之后就是每日填报

**Comment by mrcaidev** [comment]
了解！感谢提供的思路，现已对 README 进行相应的修改。

**Comment by MrPeterJin** [comment]
你好！
这个自动填报做的非常棒！这几天想要试试，但是发现微信已经阻止读取链接了，似乎无解？是否只能手动抓包了？

**Comment by mrcaidev** [comment]
> 你好！ 这个自动填报做的非常棒！这几天想要试试，但是发现微信已经阻止读取链接了，似乎无解？是否只能手动抓包了？

我刚刚测试了一下，还是可以复制链接的。不是从小程序里进入填报页面，而是要从“成电智慧学工”公众号的提醒里进入。

![Screenshot_20220119_133454](https://user-images.githubusercontent.com/78269445/150070317-13482338-942c-4bcc-836a-4e46f2d38531.jpg)

只要这个公众号提醒过你一次（不管是多久以前的），那你就一直可以从这次的提醒里进入填报页面，sessionId 会自动更新的。

**Comment by MrPeterJin** [comment]
> > 你好！ 这个自动填报做的非常棒！这几天想要试试，但是发现微信已经阻止读取链接了，似乎无解？是否只能手动抓包了？
> 
> 我刚刚测试了一下，还是可以复制链接的。不是从小程序里进入填报页面，而是要从“成电智慧学工”公众号的提醒里进入。
> 
> ![Screenshot_20220119_133454](https://user-images.githubusercontent.com/78269445/150070317-13482338-942c-4bcc-836a-4e46f2d38531.jpg)
> 
> 只要这个公众号提醒过你一次（不管是多久以前的），那你就一直可以从这次的提醒里进入填报页面，sessionId 会自动更新的。

明白了 感谢！

**Comment by MrPeterJin** [comment]
您好！

这边成功运行上了，这里觉得为了提升操作易读性，是否可以将“离校规则”和“在校规则”的文档规范化？ 看到您的 `src` 文件夹中写了关于上报的 `unreturned` 和 `returned` 配置文件了。在打卡中这是如何使用的呢？换言之，个人认为文档还需要完善一下，比如如何知道自己上报了什么到小程序中呢？

**Comment by mrcaidev** [comment]
> 您好！
> 
> 这边成功运行上了，这里觉得为了提升操作易读性，是否可以将“离校规则”和“在校规则”的文档规范化？ 看到您的 `src` 文件夹中写了关于上报的 `unreturned` 和 `returned` 配置文件了。在打卡中这是如何使用的呢？换言之，个人认为文档还需要完善一下，比如如何知道自己上报了什么到小程序中呢？

好的！关于文档的细化，我开启了一个新的 Issue（#11），会在本周日前解决。如果你有新的文档建议也欢迎在#11中提出。
